import csv
import io
from datetime import datetime

from reportlab.lib.enums import TA_CENTER
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer


def generate_csv_report(threats):

    output = io.StringIO()

    writer = csv.writer(output)

    writer.writerow([
        "Timestamp",
        "IP Address",
        "Country",
        "City",
        "Attack Type",
        "Severity",
        "Status",
        "Tag",
        "IOC Status"
    ])

    for threat in threats:

        tag = threat.get("type", "Unknown")

        severity = threat.get("severity", "")

        if severity == "Critical":
            ioc_status = "Malicious"
        elif severity == "High":
            ioc_status = "Suspicious"
        else:
            ioc_status = "Safe"

        writer.writerow([
            threat.get("timestamp", ""),
            threat.get("ip", ""),
            threat.get("country", ""),
            threat.get("city", ""),
            threat.get("type", ""),
            severity,
            threat.get("status", ""),
            tag,
            ioc_status
        ])

    output.seek(0)

    return output


def generate_pdf_report(analysis):

    buffer = io.BytesIO()

    doc = SimpleDocTemplate(buffer)

    styles = getSampleStyleSheet()

    title = styles["Heading1"]
    title.alignment = TA_CENTER

    heading = styles["Heading2"]

    normal = styles["BodyText"]

    story = []

    story.append(Paragraph("ThreatNexus AI", title))

    story.append(
        Paragraph(
            "Cyber Threat Intelligence Report",
            heading,
        )
    )

    story.append(Spacer(1, 0.3 * inch))

    story.append(
        Paragraph(
            f"<b>Generated:</b> {datetime.now().strftime('%d %B %Y %I:%M %p')}",
            normal,
        )
    )

    story.append(Spacer(1, 0.2 * inch))

    story.append(
        Paragraph(
            f"<b>Threat Score:</b> {analysis['threat_score']}/100",
            normal,
        )
    )

    story.append(
        Paragraph(
            f"<b>Risk Level:</b> {analysis['risk_level']}",
            normal,
        )
    )

    story.append(
        Paragraph(
            f"<b>Top Country:</b> {analysis['top_country']}",
            normal,
        )
    )

    story.append(
        Paragraph(
            f"<b>Top Attack:</b> {analysis['top_attack']}",
            normal,
        )
    )

    story.append(Spacer(1, 0.3 * inch))

    story.append(
        Paragraph(
            "<b>Cyber Threat Intelligence</b>",
            heading,
        )
    )

    story.append(
        Paragraph(
            "<b>Threat Intelligence Source:</b> VirusTotal",
            normal,
        )
    )

    story.append(
        Paragraph(
            "<b>IOC Lookup:</b> Enabled (IP & Domain)",
            normal,
        )
    )

    story.append(
        Paragraph(
            "<b>Threat Feed:</b> Live",
            normal,
        )
    )

    story.append(
        Paragraph(
            "<b>IOC Tagging:</b> Enabled",
            normal,
        )
    )

    story.append(
        Paragraph(
            "<b>Export Formats:</b> CSV & PDF",
            normal,
        )
    )

    story.append(
        Paragraph(
            "<b>Dashboard:</b> Real-Time CTI Monitoring",
            normal,
        )
    )

    story.append(Spacer(1, 0.3 * inch))

    story.append(
        Paragraph(
            "<b>AI Recommendation</b>",
            heading,
        )
    )

    story.append(
        Paragraph(
            analysis["recommendation"],
            normal,
        )
    )

    story.append(Spacer(1, 0.4 * inch))

    story.append(
        Paragraph(
            "Generated by ThreatNexus AI",
            heading,
        )
    )

    doc.build(story)

    buffer.seek(0)

    return buffer